"""
WalletWatch

Purpose:
Generate realistic sample transaction data for the WalletWatch database.

Input:
Wallet and merchant information

Output:
Transaction CSV / SQL insert data

Author:
Fardin Ahmed
"""

import random
from datetime import datetime, timedelta


TOTAL_TRANSACTIONS = 500


wallet_distribution = {
    "Touch 'n Go eWallet":30,
    "GrabPay":20,
    "ShopeePay":15,
    "Boost":10,
    "MAE":10,
    "CIMB OCTO":5,
    "BigPay":5,
    "Setel":5
}


wallet_names = list(wallet_distribution.keys())

wallet_weights = list(wallet_distribution.values())




 

user_ids = [1, 2, 3, 4, 5, 6, 7]


merchant_ids = [1, 2, 3, 4, 5, 6, 7, 8]


wallet_merchants = {
    "Touch 'n Go eWallet": [1, 2, 3, 4, 5, 6, 7],
    "GrabPay": [1, 2, 4, 6, 7, 8],
    "ShopeePay": [1, 2, 4, 5, 6, 7],
    "Boost": [1, 2, 4, 5],
    "MAE": [1, 3, 4, 6],
    "CIMB OCTO": [3, 6, 7],
    "BigPay": [1, 2, 7],
    "Setel": [3]
}

wallet_to_app_id = {
    "Touch 'n Go eWallet": 1,
    "GrabPay": 2,
    "ShopeePay": 3,
    "Boost": 4,
    "BigPay": 5,
    "MAE": 6,
    "CIMB OCTO": 7,
    "Setel": 8
}


amount_ranges = {
    "Touch 'n Go eWallet": (5, 250),
    "GrabPay": (5, 200),
    "ShopeePay": (5, 180),
    "Boost": (5, 150),
    "MAE": (10, 500),
    "CIMB OCTO": (20, 1000),
    "BigPay": (20, 800),
    "Setel": (30, 180)
}



currency = "MYR"

status_distribution = {
    "Success": 96,
    "Failed": 3,
    "Pending": 1
}

status_names = list(status_distribution.keys())

status_weights = list(status_distribution.values())

sql_file = open("Sql/07_insert_transactions.sql", "w", encoding="utf-8")

sql_file.write("-- WalletWatch Generated Transactions\n")
sql_file.write("-- Generated by Python\n\n")
sql_file.write("BEGIN;\n\n")

for transaction_id in range(1, TOTAL_TRANSACTIONS + 1):
 
    print(transaction_id)

    selected_wallet = random.choices(
    wallet_names,
    weights=wallet_weights,
    k=1
    )[0]

    available_merchants = wallet_merchants[selected_wallet]
    selected_merchant = random.choice(available_merchants)


    selected_amount = round(
    random.uniform(
    amount_ranges[selected_wallet][0],
    amount_ranges[selected_wallet][1]
    ),
    2
    )






    payment_methods = [
    "QR Payment",
    "Online Payment",
    "NFC",
    "Bank Transfer",
    "In-App Payment"
    ]

    selected_payment_method = random.choice(payment_methods)


    transaction_types = [
    "Purchase",
    "Top Up",
    "Bill Payment",
    "Transfer"
    ]

    selected_transaction_type = random.choice(transaction_types)


    selected_app_id = wallet_to_app_id[selected_wallet]

    selected_status = random.choices(
    status_names,
    weights=status_weights,
    k=1
    )[0]


    if selected_status == "Success":
       cashback = round(random.uniform(0, 5), 2)
    else:
       cashback = 0

    reward_points = int(selected_amount)

    start_date = datetime(2025, 1, 1)
    end_date = datetime.now()

    random_days = random.randint(
    0,
    (end_date - start_date).days
    )

    transaction_date = start_date + timedelta(days=random_days)



    formatted_date = transaction_date.strftime("%Y-%m-%d")



    selected_user = random.choice(user_ids)


    sql = f"""
INSERT INTO transactions
(user_id,
 app_id,
 merchant_id,
 transaction_type,
 payment_method,
 amount,
 currency,
 status,
 cashback,
 reward_points,
 transaction_date)
VALUES
({selected_user},
 {selected_app_id},
 {selected_merchant},
 '{selected_transaction_type}',
 '{selected_payment_method}',
 {selected_amount},
 '{currency}',
 '{selected_status}',
 {cashback},
 {reward_points},
 '{formatted_date}');
"""
    
    sql_file.write(sql)


    print("\n========================")
    print(f"Transaction #{transaction_id}")
    print("========================")
    print(f"User ID            : {selected_user}")
    print(f"Wallet             : {selected_wallet}")
    print(f"App ID             : {selected_app_id}")
    print(f"Merchant ID        : {selected_merchant}")
    print(f"Transaction Type   : {selected_transaction_type}")
    print(f"Payment Method     : {selected_payment_method}")
    print(f"Amount             : RM {selected_amount}")
    print(f"Currency           : {currency}")
    print(f"Status             : {selected_status}")
    print(f"Cashback           : RM {cashback}")
    print(f"Reward Points      : {reward_points}")
    print(f"Transaction Date   : {formatted_date}")
    print("========================")


sql_file.write("COMMIT;\n")


sql_file.close()